import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import { logInternalError } from '../utils/serverLogger';

const execAsync = promisify(exec);

export const PTAU_PATH = path.join(process.cwd(), 'lib/snarkjs/powersOfTau28_hez_final_14.ptau');

export interface SetupOutput {
  zkeyBuffer: Buffer;
  vkJson: string;
}

export interface ProveOutput {
  proofJson: string;
  publicInputsJson: string;
}

export class SnarkjsSetup {
  
  /**
   * Orchestrates Phase 2 of the Groth16 Trusted Setup locally on the server.
   * Maps an R1CS constraint payload against the universal `ptau` file
   * to produce the ZKey (Proving Key).
   * 
   * @param r1csBuffer Raw buffer extracted from compiler `main.r1cs`
   */
  async generateZkey(r1csBuffer: Buffer): Promise<Buffer> {
    const tempDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'snarkjs-zkey-'));
    
    try {
      const r1csPath = path.join(tempDir, 'circuit.r1cs');
      const zkeyPath = path.join(tempDir, 'circuit.zkey');
      
      await fs.promises.writeFile(r1csPath, r1csBuffer);

      if (!fs.existsSync(PTAU_PATH)) {
        throw new Error(`Universal ptau file not found at ${PTAU_PATH}. Check your /lib/snarkjs directory.`);
      }

      // Using the modern 'zkey new' instead of 'groth16 setup' for better compatibility with Circom 2 artifacts
      await execAsync(`npx snarkjs zkey new "${r1csPath}" "${PTAU_PATH}" "${zkeyPath}"`);

      const zkeyBuffer = await fs.promises.readFile(zkeyPath);
      return zkeyBuffer;
    } catch (err: any) {
      logInternalError('Snarkjs Setup (ZKey)', err);
      throw new Error("Failed to generate ZKey.");
    } finally {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    }
  }

  /**
   * Extracts the Verification Key (VK) in JSON format from a generated ZKey.
   * 
   * @param zkeyBuffer Raw buffer of the generated `.zkey`
   */
  async exportVerificationKey(zkeyBuffer: Buffer): Promise<string> {
    const tempDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'snarkjs-vkey-'));
    
    try {
      const zkeyPath = path.join(tempDir, 'circuit.zkey');
      const vkPath = path.join(tempDir, 'verification_key.json');
      
      await fs.promises.writeFile(zkeyPath, zkeyBuffer);

      await execAsync(`npx snarkjs zkey export verificationkey "${zkeyPath}" "${vkPath}"`);

      const vkJsonRaw = await fs.promises.readFile(vkPath, 'utf-8');
      return vkJsonRaw;
    } catch (err: any) {
      logInternalError('Snarkjs Export VK', err);
      throw new Error("Failed to export verification key.");
    } finally {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    }
  }

  /**
   * Generates a Groth16 Proof and Public Inputs array using SnarkJS.
   * This handles both calculating the witness (using the Wasm binary) and
   * generating the SNARK proof (using the ZKey).
   * 
   * @param signals Record of string keys mapping to string/number signal values
   * @param wasmBuffer Raw buffer of the `.wasm` file generated by Circom
   * @param zkeyBuffer Raw buffer of the `.zkey` file generated by the Trusted Setup
   */
  async generateProof(
    signals: Record<string, string | number>,
    wasmBuffer: Buffer,
    zkeyBuffer: Buffer
  ): Promise<ProveOutput> {
    const tempDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'snarkjs-prove-'));
    
    try {
      const wasmPath = path.join(tempDir, 'circuit.wasm');
      const zkeyPath = path.join(tempDir, 'circuit.zkey');
      const inputPath = path.join(tempDir, 'input.json');
      const proofPath = path.join(tempDir, 'proof.json');
      const publicPath = path.join(tempDir, 'public.json');
      
      await fs.promises.writeFile(wasmPath, wasmBuffer);
      await fs.promises.writeFile(zkeyPath, zkeyBuffer);
      await fs.promises.writeFile(inputPath, JSON.stringify(signals));

      try {
        // Execute full prove via snarkjs CLI
        // This calculates the witness and generates the proof in one step.
        const { stdout, stderr } = await execAsync(`npx snarkjs groth16 fullprove "${inputPath}" "${wasmPath}" "${zkeyPath}" "${proofPath}" "${publicPath}"`);

        if (stderr && stderr.includes('Error')) {
           console.error('[SnarkjsSetup] groth16 fullprove error details:', stderr);
        }

        const proofRaw = await fs.promises.readFile(proofPath, 'utf-8');
        const publicRaw = await fs.promises.readFile(publicPath, 'utf-8');

        return {
          proofJson: proofRaw,
          publicInputsJson: publicRaw
        };
      } catch (err: any) {
         logInternalError('Snarkjs Prove (exec)', err);
         // Surface specific snarkjs errors if available
         const detail = err.stdout || err.stderr || "";
         if (detail.includes('Invalid witness length')) {
            throw new Error("Invalid witness length: your inputs might not match the circuit signals or the WASM/ZKey are mismatched. Try re-compiling and re-running Setup.");
         }
         throw new Error("Failed to generate zero-knowledge proof. Check your inputs.");
      }
    } finally {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    }
  }
}
