import { execFile } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const execFileAsync = promisify(execFile);

// ─── Constants ────────────────────────────────────────────────────────────────

/** Timeout for scarb build. */
export const COMPILE_TIMEOUT_MS = 60_000;

/** Temp dir prefix for compilation runs. */
export const SCARB_TEMP_DIR_PREFIX = 'scarb-compile-';

/**
 * Path to the scarb CLI binary.
 * Resolves to the generic `scarb` which should be on the path, or a specific local installation.
 */
export const SCARB_CLI_PATH =
  process.env.SCARB_PATH ??
  '/home/godspowereze/.asdf/shims/scarb';

// ─── Input/Output types ───────────────────────────────────────────────────────

export interface ScarbCompileInput {
  projectName: string;
  verifierCairo: string;
  constantsCairo: string;
  libCairo: string;
  scarbToml: string;
}

export type ScarbCompileResult =
  | { success: true; sierra: any; casm: any }
  | { success: false; error: string };

// ─── ScarbCompiler ────────────────────────────────────────────────────────────

/**
 * ScarbCompiler — runs `scarb build` as a subprocess to produce Sierra and Casm
 * JSON outputs from raw Cairo files generated by garaga.
 */
export class ScarbCompiler {
  async compile(input: ScarbCompileInput): Promise<ScarbCompileResult> {
    const tempDir = await fs.promises.mkdtemp(
      path.join(os.tmpdir(), SCARB_TEMP_DIR_PREFIX)
    );

    try {
      // Step 1: Write Scarb Project
      const srcDir = path.join(tempDir, 'src');
      await fs.promises.mkdir(srcDir, { recursive: true });

      await Promise.all([
        fs.promises.writeFile(path.join(tempDir, 'Scarb.toml'), input.scarbToml, 'utf8'),
        fs.promises.writeFile(path.join(srcDir, 'groth16_verifier.cairo'), input.verifierCairo, 'utf8'),
        fs.promises.writeFile(path.join(srcDir, 'groth16_verifier_constants.cairo'), input.constantsCairo, 'utf8'),
        fs.promises.writeFile(path.join(srcDir, 'lib.cairo'), input.libCairo, 'utf8'),
      ]);

      // Step 2: Run scarb build
      try {
        await execFileAsync(SCARB_CLI_PATH, ['build'], {
          cwd: tempDir,
          timeout: COMPILE_TIMEOUT_MS,
          maxBuffer: 10 * 1024 * 1024,
        });
      } catch (err: unknown) {
        const msg = isExecError(err)
          ? (err.stderr || err.stdout || String(err))
          : String(err);
        
        if (isExecError(err) && (err.killed || err.signal === 'SIGTERM')) {
          return { success: false, error: `scarb build timed out after ${COMPILE_TIMEOUT_MS / 1000}s` };
        }
        return { success: false, error: `scarb build failed: ${msg}` };
      }

      // Step 3: Read generated artifacts
      // Scarb compiles contract classes down to target/dev/{project_name}_{contract_name}.contract_class.json
      // The garaga output project structure defines a contract named 'Groth16Verifier'.
      // Usually scarb outputs files in `target/dev/`. Let's find the json files dynamically.
      const devDir = path.join(tempDir, 'target', 'dev');
      const files = await fs.promises.readdir(devDir);

      const sierraFile = files.find(f => f.endsWith('.contract_class.json'));
      const casmFile = files.find(f => f.endsWith('.compiled_contract_class.json'));

      if (!sierraFile || !casmFile) {
        return { success: false, error: 'scarb build succeeded but did not produce .contract_class.json and .compiled_contract_class.json files' };
      }

      const [sierraJson, casmJson] = await Promise.all([
        fs.promises.readFile(path.join(devDir, sierraFile), 'utf8').then(JSON.parse),
        fs.promises.readFile(path.join(devDir, casmFile), 'utf8').then(JSON.parse),
      ]);

      return {
        success: true,
        sierra: sierraJson,
        casm: casmJson,
      };

    } catch (err: unknown) {
      return { success: false, error: String(err) };
    } finally {
      // Step 4: Always clean up
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    }
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

interface ExecError extends Error {
  killed?: boolean;
  signal?: string;
  stdout?: string;
  stderr?: string;
}

function isExecError(err: unknown): err is ExecError {
  return err instanceof Error;
}
