import { execFile } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { logInternalError } from '../utils/serverLogger';
import type { ScarbCompileInput, ScarbCompileResult } from './types';

const execFileAsync = promisify(execFile);

// ─── Constants ────────────────────────────────────────────────────────────────

/** Timeout for scarb build (5 minutes) */
export const COMPILE_TIMEOUT_MS = 300_000;

/**
 * Path to the scarb CLI binary.
 * Must be set via the SCARB_PATH environment variable (see .env.local).
 */
export const SCARB_CLI_PATH = (() => {
  const p = process.env.SCARB_PATH;
  if (!p) throw new Error('SCARB_PATH environment variable is not set. Add it to .env.local.');
  return p;
})();



/**
 * ScarbCompiler — runs `scarb build` as a subprocess to produce Sierra and Casm
 * JSON outputs from raw Cairo files generated by garaga.
 */
export class ScarbCompiler {
  async compile(input: ScarbCompileInput): Promise<ScarbCompileResult> {
    // Generate inside a consistent directory to leverage Scarb's internal target caching
    const workspaceDir = path.join(process.cwd(), '.scarb-workspace');
    const tempDir = path.join(workspaceDir, input.projectName);

    try {
      // Step 1: Write Scarb Project
      const srcDir = path.join(tempDir, 'src');
      await fs.promises.mkdir(srcDir, { recursive: true });

      // Clean src dir just in case old files remain
      const existingFiles = await fs.promises.readdir(srcDir).catch(() => []);
      for (const file of existingFiles) {
        await fs.promises.unlink(path.join(srcDir, file));
      }

      await Promise.all([
        fs.promises.writeFile(path.join(tempDir, '.tool-versions'), 'scarb 2.14.0\n', 'utf8'),
        fs.promises.writeFile(path.join(tempDir, 'Scarb.toml'), input.scarbToml, 'utf8'),
      ]);

      // Write verifier files - detect if it's Noir (honk) or Circom (groth16)
      const isNoir = input.verifierCairo.includes('honk') || input.constantsCairo.includes('honk');
      const verifierFilename = isNoir ? 'honk_verifier.cairo' : 'groth16_verifier.cairo';
      const constantsFilename = isNoir ? 'honk_verifier_constants.cairo' : 'groth16_verifier_constants.cairo';

      await Promise.all([
        fs.promises.writeFile(path.join(srcDir, verifierFilename), input.verifierCairo, 'utf8'),
        fs.promises.writeFile(path.join(srcDir, constantsFilename), input.constantsCairo, 'utf8'),
        fs.promises.writeFile(path.join(srcDir, 'lib.cairo'), input.libCairo, 'utf8'),
      ]);

      // Write circuits file if present (Noir/Honk only)
      if (input.circuitsCairo) {
        await fs.promises.writeFile(path.join(srcDir, 'honk_verifier_circuits.cairo'), input.circuitsCairo, 'utf8');
      }

      // Step 2: Run scarb build
      try {
        await execFileAsync(SCARB_CLI_PATH, ['build'], {
          cwd: tempDir,
          timeout: COMPILE_TIMEOUT_MS,
          maxBuffer: 10 * 1024 * 1024,
        });
      } catch (err: unknown) {
        const msg = isExecError(err)
          ? (err.stderr || err.stdout || String(err))
          : String(err);
        
        logInternalError('Scarb Build (exec)', err);
        
        if (isExecError(err) && (err.killed || err.signal === 'SIGTERM')) {
          return { success: false, error: `scarb build timed out.` };
        }
        return { success: false, error: `Failed to compile verifier contract.` };
      }

      // Step 3: Read generated artifacts
      // Scarb compiles contract classes down to target/dev/{project_name}_{contract_name}.contract_class.json
      // The garaga output project structure defines a contract named 'Groth16Verifier'.
      // Usually scarb outputs files in `target/dev/`. Let's find the json files dynamically.
      const devDir = path.join(tempDir, 'target', 'dev');
      const files = await fs.promises.readdir(devDir);

      const sierraFile = files.find(f => f.endsWith('.contract_class.json'));
      const casmFile = files.find(f => f.endsWith('.compiled_contract_class.json'));

      if (!sierraFile || !casmFile) {
        return { success: false, error: 'scarb build succeeded but did not produce .contract_class.json and .compiled_contract_class.json files' };
      }

      const [sierraJson, casmJson] = await Promise.all([
        fs.promises.readFile(path.join(devDir, sierraFile), 'utf8').then(JSON.parse),
        fs.promises.readFile(path.join(devDir, casmFile), 'utf8').then(JSON.parse),
      ]);

      return {
        success: true,
        sierra: sierraJson,
        casm: casmJson,
      };

    } catch (err: unknown) {
      logInternalError('Scarb Build (catch)', err);
      return { success: false, error: "Failed to compile verifier contract." };
    } finally {
      // Intentionally *not* cleaning up the directory so Scarb caches the dependencies
      // It will just be overwritten next compile.
    }
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

interface ExecError extends Error {
  killed?: boolean;
  signal?: string;
  stdout?: string;
  stderr?: string;
}

function isExecError(err: unknown): err is ExecError {
  return err instanceof Error;
}
