// ─── Language discriminator ────────────────────────────────────────────────────

/**
 * Supported circuit languages.
 * Circom is implemented in Phase 1. Noir is planned for Phase 3 (after Circom
 * end-to-end is complete).
 */
export type LanguageId = 'circom' | 'noir';

// ─── Input ────────────────────────────────────────────────────────────────────

/**
 * A single file in a multi-file circuit project.
 * Language-agnostic — used for both Circom (.circom) and Noir (.nr) files.
 */
export interface SourceFile {
  /** Filename (e.g. "circuit.circom", "src/main.nr"). Must be unique within the project. */
  filename: string;
  /** Raw source content. */
  content: string;
}

/** @deprecated Use SourceFile instead. */
export type CircomFile = SourceFile;

/**
 * Language-agnostic circuit source. The `language` field routes the request to
 * the correct compiler (CircomServerCompiler, NoirServerCompiler, etc.).
 *
 * Multi-file projects pass all files in `files[]`. Single-file projects wrap
 * their source in a one-element array.
 */
export interface CompileSource {
  /** Circuit language. */
  language: LanguageId;
  /** All project files. Must contain at least one entry. */
  files: SourceFile[];
  /** Filename of the entry point — must match an entry in `files`. */
  entrypoint: string;
}

// ─── Errors ───────────────────────────────────────────────────────────────────

export type CompileErrorCategory =
  | 'syntax'
  | 'semantic'
  | 'unsupported'
  | 'validation'
  | 'timeout'
  | 'internal';

export interface CompileError {
  message: string;
  category: CompileErrorCategory;
  /** Source file name, if known. */
  file?: string;
  /** 1-indexed line number, if known. */
  line?: number;
  /** 1-indexed column number, if known. */
  column?: number;
}

export interface RawCompileOutput {
  stdout: string;
  stderr: string;
  /** Primary artifact (R1CS for Circom, ACIR JSON for Noir), if compilation succeeded. */
  artifactBuffer?: Buffer;
  /** Symbol/debug file contents, if generated. */
  symContent?: string;
  /** WebAssembly binary buffer for native witness calculation. */
  wasmBuffer?: Buffer;
  /** JS wrapper code required by SnarkJS to run the wasm witness. */
  wasmJs?: string;
}

// ─── Language-specific compile results ───────────────────────────────────────

/**
 * Circom Groth16 compilation result.
 * Produced by Feature 01/02.
 */
export interface CircomCompileResult {
  /** Number of R1CS constraints generated. */
  constraintCount: number;
  /** Wire count, if available. */
  wireCount?: number;
  /** Warnings emitted by the compiler. */
  warnings: string[];
  /** R1CS binary buffer generated by Circom. */
  r1csBuffer?: Buffer;
  /** Symbol names output, mapping wires to constraint signals. */
  symContent?: string;
  /** WebAssembly binary buffer for native witness calculation. */
  wasmBuffer?: Buffer;
  /** JS wrapper code required by SnarkJS to run the wasm witness. */
  wasmJs?: string;
}

// ─── Noir ABI ─────────────────────────────────────────────────────────────────

/**
 * Recursive type descriptor for a Noir ABI parameter.
 *
 * Noir's type system maps to these kinds:
 *   field   — a single BN254 field element (252-bit integer)
 *   integer — a bounded integer (u8, u32, i64, …); width in bits
 *   boolean — a single bit (0 or 1)
 *   array   — fixed-length homogeneous sequence; carries length + element type
 *   string  — fixed-length UTF-8 byte array (rare in circuits)
 *   tuple   — heterogeneous fixed-length sequence
 *   struct  — named-field composite type
 */
export interface NoirAbiType {
  kind: 'field' | 'integer' | 'boolean' | 'string' | 'array' | 'tuple' | 'struct';
  /** integer: 'unsigned' | 'signed' */
  sign?: 'unsigned' | 'signed';
  /** integer: bit width (e.g. 32 for u32) */
  width?: number;
  /** array / string: number of elements */
  length?: number;
  /** array: element type */
  type?: NoirAbiType;
  /** tuple: ordered element types */
  fields?: NoirAbiType[];
}

/**
 * A single parameter in the Noir ABI.
 *
 * All `fn main(...)` parameters appear here — both `pub` and private.
 * `visibility` controls whether the value ends up in the proof's public
 * inputs, but every parameter must be supplied by the prover at witness
 * generation time.
 */
export interface NoirAbiParameter {
  name: string;
  type: NoirAbiType;
  /** 'public' → value appears in the proof's public inputs; 'private' → witness-only. */
  visibility: 'private' | 'public';
}

/**
 * The ABI section of a compiled Noir artifact (`target/circuit.json`).
 *
 * Why the ABI is the authoritative source for input inference (vs Circom's sym):
 *   - It is a first-class compiler output, not a side-effect wire table.
 *   - Array lengths are already resolved (no template-parameter ambiguity).
 *   - Types are explicit (field / integer / boolean / array / struct).
 *   - No cross-referencing with source text is needed.
 */
export interface NoirAbi {
  /** All `fn main` parameters in declaration order. */
  parameters: NoirAbiParameter[];
  /**
   * Return type of `fn main`, if any.
   * This is an output — excluded from input inference.
   */
  return_type: { abi_type: NoirAbiType; visibility: 'private' | 'public' } | null;
}

// ─── Noir compile result ───────────────────────────────────────────────────────

/**
 * Noir compilation result produced by NoirServerCompiler.
 *
 * Noir produces ACIR (Abstract Circuit IR) via `nargo compile`.
 * The artifact is a JSON file (`target/circuit.json`) containing the bytecode
 * and ABI.  Unlike Circom there is no trusted setup — UltraHonk is a
 * transparent proof system.
 */
export interface NoirCompileResult {
  /**
   * Number of gates (circuit size) from bb gates.
   */
  gateCount: number;
  /**
   * Number of ACIR opcodes from bb gates.
   */
  acirOpcodeCount: number;
  /** Warnings emitted by nargo (lines matching `[warning]` in stdout). */
  warnings: string[];
  /**
   * Parsed ABI from the compiled artifact.
   * Used by the client to infer input signal names and types without
   * re-parsing the source.
   */
  abi: NoirAbi;
  /**
   * Base64-encoded raw content of `target/circuit.json`.
   * Passed back to `/api/circuit/prove` so witness generation can proceed
   * without re-compiling.
   */
  acirBase64: string;
}

/** Union of all language-specific compile results. */
export type LanguageCompileResult = CircomCompileResult | NoirCompileResult;

// ─── API response shapes ──────────────────────────────────────────────────────

export interface CompileSuccessResponse {
  success: true;
  language: LanguageId;
  result: LanguageCompileResult;
}

export interface CompileErrorResponse {
  success: false;
  language: LanguageId;
  errors: CompileError[];
}

export type CompileResponse = CompileSuccessResponse | CompileErrorResponse;
